development:
  adapter: postgresql
  encoding: utf8
  database: signupApp_development
  username: postgres
  password: postgres
  host: localhost
  pool: 5

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: signupApp_test
  username: postgres
  password: postgres
  host: localhost
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: signupApp_development
  username: postgres
  password: postgres
  host: localhost
  pool: 5

cucumber:
  <<: *TEST
